### ISSUE TITLE
Webgl build not working

### ISSUE THREAD

**Issue by rafaelnsantos** [rafaelnsantos/Travis-Unity#1]
files in Build folder nameless

**Comment by jaimerson** [comment]
I had the same problem and didn't find a real fix for it, maybe it's a bug in Unity. I did manage to find a workaround manually moving the files and overwriting the `index.html` and `projectName.json` to update the names. https://github.com/jaimerson/Skim/commit/0e9fa56c3a6db41a5c148340622a8063d0b7b33f and https://github.com/jaimerson/Skim/commit/5df68e92f6243e095314437db12cdba10ed12ae4
